# Generated by Django 5.2.2 on 2025-06-09 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('tipo_laudo', models.CharField(max_length=50)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_estimado_dano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.agente')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoStatusLaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=50)),
                ('status_novo', models.CharField(max_length=50)),
                ('data_status', models.DateField(blank=True, null=True)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.laudo')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evidencia', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('caminho_arquivo', models.TextField()),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.laudo')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.colaborador')),
                ('laudo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.laudo')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.metodo')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='laudo',
            name='perito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudo_perito', to='cadastros.pessoainstitucional'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastros.pessoainstitucional'),
        ),
        migrations.AddField(
            model_name='agente',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastros.pessoainstitucional'),
        ),
        migrations.CreateModel(
            name='ResultadoPericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('resultado', models.TextField()),
                ('descricao', models.TextField()),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.laudo')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.proprietario')),
            ],
        ),
        migrations.AddField(
            model_name='laudo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.veiculo'),
        ),
        migrations.CreateModel(
            name='AvaliacaoResponsabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_responsabilidade', models.CharField(max_length=50)),
                ('descricao_responsabilidade', models.TextField()),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.agente')),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.laudo')),
            ],
            options={
                'unique_together': {('laudo', 'agente')},
            },
        ),
    ]
