# Generated by Django 5.2.2 on 2025-06-09 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laudo',
            name='perito',
        ),
        migrations.AddField(
            model_name='laudo',
            name='envolvidos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudo_perito', to='cadastros.pessoainstitucional'),
        ),
        migrations.DeleteModel(
            name='AvaliacaoResponsabilidade',
        ),
    ]
