# Generated by Django 5.2.2 on 2025-06-09 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_laudo_perito_laudo_envolvidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laudo',
            name='envolvidos',
        ),
        migrations.AddField(
            model_name='laudo',
            name='envolvido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudo_perito', to='cadastros.pessoainstitucional'),
        ),
    ]
